/*
# Seed Schemes and Offices Reference Data

## Purpose
Populates the `schemes` and `offices` tables with realistic Indian government
welfare schemes, scholarships, pensions, farmer programs, and government service
centres. This is reference data shared across all authenticated citizens.

## Changes
1. Inserts 24 representative Central + State schemes covering scholarships,
   pensions, healthcare, housing, farmer benefits, employment, business,
   women, disability, and senior-citizen categories.
2. Inserts 12 representative government service centres across Tamil Nadu
   districts (Aadhaar, Passport Seva Kendra, RTO, Taluk, CSC, bank, hospital,
   police, agriculture, employment exchange, municipal).
3. Each scheme includes multilingual name/description (English/Hindi/Tamil),
   eligibility JSON, required documents, estimated processing days, and tags.

## Security
No policy changes. These tables already allow SELECT to authenticated users.
*/

-- ============ schemes ============
INSERT INTO schemes (name, name_hi, name_ta, description, description_hi, description_ta, category, ministry, level, state, benefits, eligibility, documents_required, application_url, deadline, estimated_days, tags)
VALUES
('Post Matric Scholarship for SC Students', 'एससी छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति', 'பட்டியல் வகுப்பு மாணவர்களுக்கான மெட்ரிக் மேல் உதவித்தொகை', 'Financial assistance to SC students studying at post-matriculation level for tuition, maintenance, and other educational expenses.', 'मैट्रिक के बाद की पढ़ाई कर रहे एससी छात्रों को ट्यूशन, रखरखाव और अन्य शैक्षणिक खर्चों के लिए वित्तीय सहायता।', 'மெட்ரிக்கிற்குப் பின் படிக்கும் பட்டியல் வகுப்பு மாணவர்களுக்கு கட்டணம், பராமரிப்பு மற்றும் பிற கல்வி செலவுகளுக்கான நிதி உதவி.', 'scholarship', 'Ministry of Social Justice and Empowerment', 'central', '', 'Tuition fee + maintenance allowance up to ₹20,000/year', '{"categories":["SC"],"education":["post-matric"],"income_max":250000}', ARRAY['Aadhaar Card','Community Certificate','Income Certificate','Bank Passbook','Bonafide Certificate'], 'https://scholarships.gov.in', '2025-12-31', 45, ARRAY['sc','student','education']),
('Pre-Matric Scholarship for ST Students', 'एसटी छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति', 'பழங்குடி மாணவர்களுக்கான மெட்ரிக் முன் உதவித்தொகை', 'Scholarship for ST students studying in classes I to X to reduce dropout rates.', 'कक्षा I से X तक पढ़ रहे एसटी छात्रों के लिए ड्रॉपआउट कम करने हेतु छात्रवृत्ति।', 'I முதல் X வகுப்பு வரை படிக்கும் பழங்குடி மாணவர்களுக்கான உதவித்தொகை.', 'scholarship', 'Ministry of Tribal Affairs', 'central', '', '₹150-₹500/month based on class', '{"categories":["ST"],"education":["pre-matric"],"income_max":200000}', ARRAY['Aadhaar Card','Community Certificate','Income Certificate','Bonafide Certificate'], 'https://scholarships.gov.in', '2025-12-31', 30, ARRAY['st','student','education']),
('National Scholarship for Higher Education', 'उच्च शिक्षा के लिए राष्ट्रीय छात्रवृत्ति', 'உயர் கல்விக்கான தேசிய உதவித்தொகை', 'Merit-cum-means scholarship for students pursuing professional and technical courses.', 'प्रोफेशनल और टेक्निकल कोर्स कर रहे छात्रों के लिए मेरिट-कम-मीन्स छात्रवृत्ति।', 'தொழில்முறை மற்றும் தொழில்நுட்ப பாடநெறிகளை மேற்கொள்ளும் மாணவர்களுக்கான தகுதி-சராசரி உதவித்தொகை.', 'scholarship', 'Ministry of Education', 'central', '', '₹12,000/year + additional benefits', '{"education":["graduate","postgraduate"],"income_max":600000}', ARRAY['Aadhaar Card','Income Certificate','Mark Sheets','Bank Passbook'], 'https://scholarships.gov.in', '2025-10-31', 60, ARRAY['student','higher-education','merit']),
('Scholarship for Girl Students (Beti Bachao)', 'बेटी बचाओ बेटी पढ़ाओ छात्रवृत्ति', 'பெண் குழந்தைகளுக்கான உதவித்தொகை (பேட்டி பசாஓ)', 'Incentive for the education of the girl child from birth through graduation.', 'जन्म से स्नातक तक बालिका की शिक्षा के लिए प्रोत्साहन।', 'பிறப்பு முதல் பட்டப்படிப்பு வரை பெண் குழந்தையின் கல்விக்கான ஊக்கத்தொகை.', 'scholarship', 'Ministry of Women and Child Development', 'central', '', 'Up to ₹1.5 lakh in staggered payouts', '{"gender":["female"],"income_max":800000}', ARRAY['Aadhaar Card','Birth Certificate','Bank Passbook','Income Certificate'], 'https://wcd.nic.in', '2025-09-30', 90, ARRAY['women','girl','education']),
('Indira Gandhi National Old Age Pension', 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन', 'இந்திரா காந்தி தேசிய மூத்தோர் ஓய்வூதியம்', 'Monthly pension to BPL persons aged 60 years and above.', '60 वर्ष और उससे अधिक आयु के बीपीएल व्यक्तियों को मासिक पेंशन।', '60 வயது மற்றும் அதற்கு மேற்பட்ட BPL நபர்களுக்கு மாதாந்திர ஓய்வூதியம்.', 'pension', 'Ministry of Rural Development', 'central', '', '₹200/month + state top-up', '{"age_min":60,"income_max":32000}', ARRAY['Aadhaar Card','Age Proof','Income Certificate','Bank Passbook'], 'https://nsap.nic.in', '', 30, ARRAY['senior','pension','bpl']),
('Indira Gandhi National Widow Pension', 'इंदिरा गांधी राष्ट्रीय विधवा पेंशन', 'இந்திரா காந்தி தேசிய விதவை ஓய்வூதியம்', 'Monthly pension to widows aged 40-79 from BPL families.', 'बीपीएल परिवாरों की 40-79 वर्ष की विधवाओं को मासिक पेंशन।', 'BPL குடும்பங்களைச் சேர்ந்த 40-79 வயது விதவைகளுக்கு மாதாந்திர ஓய்வூதியம்.', 'pension', 'Ministry of Rural Development', 'central', '', '₹300/month', '{"age_min":40,"age_max":79,"income_max":32000,"tags":["widow"]}', ARRAY['Aadhaar Card','Death Certificate of Spouse','Income Certificate','Bank Passbook'], 'https://nsap.nic.in', '', 30, ARRAY['widow','pension','bpl']),
('Tamil Nadu Chief Minister''s Pension Scheme', 'तमिलनाडु मुख्यमंत्री पेंशन योजना', 'தமிழ்நாடு முதலமைச்சர் ஓய்வூதியத் திட்டம்', 'Monthly pension to destitute elderly aged 60+ in Tamil Nadu.', 'तमिलनाडु में 60+ वर्ष के वंचित बुजुर्गों को मासिक पेंशन।', 'தமிழ்நாட்டில் 60+ வயதுடைய ஆதரவற்ற மூத்தோருக்கு மாதாந்திர ஓய்வூதியம்.', 'pension', 'Government of Tamil Nadu', 'state', 'Tamil Nadu', '₹1,000/month', '{"age_min":60,"state":"Tamil Nadu"}', ARRAY['Aadhaar Card','Age Proof','Residence Certificate','Bank Passbook'], '', '', 45, ARRAY['senior','pension','tamil-nadu']),
('Ayushman Bharat (PMJAY)', 'आयुष्मान भारत (पीएमजेए)', 'ஆயுஷ்மான் பாரத் (PMJAY)', 'Health insurance cover of ₹5 lakh per family per year for secondary and tertiary care.', 'माध्यमिक और तृतीयक उपचार के लिए प्रति परिवार वार्षिक ₹5 लाख का स्वास्थ्य बीमा।', 'இரண்டாம் நிலை மற்றும் மூன்றாம் நிலை சிகிச்சைக்கு குடும்பத்திற்கு ஆண்டுக்கு ₹5 லட்சம் சுகாதார காப்பீடு.', 'healthcare', 'Ministry of Health and Family Welfare', 'central', '', '₹5 lakh/year family health cover', '{"income_max":0,"tags":["bpl","secc"]}', ARRAY['Aadhaar Card','Ration Card','Family ID'], 'https://pmjay.gov.in', '', 14, ARRAY['health','insurance','bpl']),
('Tamil Nadu Chief Minister''s Health Insurance', 'तमिलनाडु मुख्यमंत्री स्वास्थ्य बीमा', 'தமிழ்நாடு முதலமைச்சர் விரிவான சுகாதார காப்பீடு', 'State health insurance up to ₹5 lakh per family for listed treatments.', 'सूचीबद्ध उपचारों के लिए प्रति परिवार ₹5 लाख तक का राज्य स्वास्थ्य बीमा।', 'பட்டியலிடப்பட்ட சிகிச்சைகளுக்கு குடும்பத்திற்கு ₹5 லட்சம் வரை மாநில சுகாதார காப்பீடு.', 'healthcare', 'Government of Tamil Nadu', 'state', 'Tamil Nadu', 'Up to ₹5 lakh/year per family', '{"state":"Tamil Nadu"}', ARRAY['Aadhaar Card','Residence Certificate','Family Card'], '', '', 14, ARRAY['health','insurance','tamil-nadu']),
('PM-KISAN Samman Nidhi', 'पीएम-किसान सम्मान निधि', 'பிஎம்-கிசான் சம்மான் நிதி', 'Income support of ₹6,000/year to small and marginal farmer families in three instalments.', 'छोटे और सीमांत किसान परिवारों को तीन किस्तों में ₹6,000/वर्ष आय सहायता।', 'சிறு மற்றும் குறு விவசாயி குடும்பங்களுக்கு மூன்று தவணைகளில் ₹6,000/ஆண்டு வருமான உதவி.', 'farmer', 'Ministry of Agriculture and Farmers Welfare', 'central', '', '₹6,000/year in 3 instalments', '{"occupation":["farmer"],"land_max":2}', ARRAY['Aadhaar Card','Land Records','Bank Passbook'], 'https://pmkisan.gov.in', '', 15, ARRAY['farmer','agriculture','income']),
('Pradhan Mantri Fasal Bima Yojana', 'प्रधानमंत्री फसल बीमा योजना', 'பிரதமர் பயிர் காப்பீட்டுத் திட்டம்', 'Crop insurance against natural calamities, pests, and diseases at low premium.', 'प्राकृतिक आपदाओं, कीटों और बीमारियों के खिलाफ कम प्रीमियम पर फसल बीमा।', 'இயற்கை பேரழிவுகள், பூச்சிகள் மற்றும் நோய்களுக்கு எதிராக குறைந்த காப்பீட்டு தொகையில் பயிர் காப்பீடு.', 'farmer', 'Ministry of Agriculture and Farmers Welfare', 'central', '', 'Full sum insured coverage, low premium 1.5-2%', '{"occupation":["farmer"]}', ARRAY['Aadhaar Card','Land Records','Bank Passbook','Sowing Certificate'], 'https://pmfby.gov.in', '', 20, ARRAY['farmer','insurance','crop']),
('Soil Health Card Scheme', 'मृदा स्वास्थ्य कार्ड योजना', 'மண் ஆரோக்கிய அட்டைத் திட்டம்', 'Free soil health card with nutrient status and fertilizer recommendations.', 'पोषक तत्व स्थिति और उर्वरक सिफारिशों के साथ निःशुल्क मृदा स्वास्थ्य कार्ड।', 'ஊட்டச்சத்து நிலை மற்றும் உரப் பரிந்துரைகளுடன் இலவச மண் ஆரோக்கிய அட்டை.', 'farmer', 'Ministry of Agriculture and Farmers Welfare', 'central', '', 'Free soil testing + recommendations', '{"occupation":["farmer"]}', ARRAY['Aadhaar Card','Land Records'], '', '', 7, ARRAY['farmer','soil','agriculture']),
('Pradhan Mantri Awas Yojana (Urban)', 'प्रधानमंत्री आवास योजना (शहरी)', 'பிரதமர் வீட்டுவசதித் திட்டம் (நகர்ப்புற)', 'Interest subsidy on home loans for EWS/LIG families to buy or build a pucca house.', 'कच्चा घर खरीदने या बनाने के लिए ईडब्ल्यूएस/एलआईजी परिवारों को गृह ऋण पर ब्याज सब्सिडी।', 'EWS/LIG குடும்பங்களுக்கு பக்கா வீடு வாங்க அல்லது கட்ட வீட்டுக் கடனில் வட்டி மானியம்.', 'housing', 'Ministry of Housing and Urban Affairs', 'central', '', 'Interest subsidy up to ₹2.67 lakh', '{"income_max":600000,"area":"urban"}', ARRAY['Aadhaar Card','Income Certificate','Bank Passbook','Property Documents'], 'https://pmaymis.gov.in', '2025-12-31', 120, ARRAY['housing','urban','loan']),
('Pradhan Mantri Awas Yojana (Gramin)', 'प्रधानमंत्री आवास योजना (ग्रामीण)', 'பிரதமர் வீட்டுவசதித் திட்டம் (கிராமப்புற)', 'Financial assistance to build a pucca house in rural areas.', 'ग्रामीण क्षेत्रों में पक्का घर बनाने के लिए वित्तीय सहायता।', 'கிராமப்புறங்களில் பக்கா வீடு கட்ட நிதி உதவி.', 'housing', 'Ministry of Rural Development', 'central', '', '₹1.2-1.3 lakh assistance', '{"area":"rural","tags":["bpl"]}', ARRAY['Aadhaar Card','Land Records','Income Certificate','Bank Passbook'], 'https://pmayg.nic.in', '', 90, ARRAY['housing','rural','bpl']),
('Mahatma Gandhi NREGA', 'महात्मा गांधी नरेगा', 'மகாத்மா காந்தி நிரேகா', 'Guaranteed 100 days of wage employment per year to rural households.', 'ग्रामीण परिवारों को वार्षिक 100 दिनों की वेतन रोजगार की गारंटी।', 'கிராமப்புற குடும்பங்களுக்கு ஆண்டுக்கு 100 நாட்கள் கூலி வேலை உத்தரவாதம்.', 'employment', 'Ministry of Rural Development', 'central', '', '100 days wage at minimum rate', '{"area":"rural"}', ARRAY['Aadhaar Card','Job Card','Bank Passbook'], 'https://nrega.nic.in', '', 7, ARRAY['employment','rural','wage']),
('Pradhan Mantri Kaushal Vikas Yojana', 'प्रधानमंत्री कौशल विकास योजना', 'பிரதமர் திறன் மேம்பாட்டுத் திட்டம்', 'Free short-term skill training with certification and placement support.', 'प्रमाणन और नौकरी सहायता के साथ निःशुल्क अल्पकालिक कौशल प्रशिक्षण।', 'சான்றிதழ் மற்றும் வேலை உதவியுடன் இலவச குறுகிய கால திறன் பயிற்சி.', 'employment', 'Ministry of Skill Development and Entrepreneurship', 'central', '', 'Free training + ₹8,000 stipend', '{"age_min":15,"age_max":45}', ARRAY['Aadhaar Card','Educational Certificates','Bank Passbook'], 'https://pmkvyofficial.org', '', 60, ARRAY['skill','training','employment']),
('Mudra Yojana (Loan for Small Business)', 'मुद्रा योजना (लघु व्यवसाय ऋण)', 'முத்ரா திட்டம் (சிறு வணிபக் கடன்)', 'Collateral-free loans up to ₹10 lakh for micro and small businesses.', 'माइक्रो और लघु व्यवसायों के लिए ₹10 लाख तक का बिना गिरवी ऋण।', 'நுண் மற்றும் சிறு வணிபங்களுக்கு ₹10 லட்சம் வரை அடமானமற்ற கடன்.', 'business', 'Ministry of Finance', 'central', '', 'Loans up to ₹10 lakh (Shishu/Kishore/Tarun)', '{"occupation":["entrepreneur"],"age_min":18}', ARRAY['Aadhaar Card','PAN Card','Business Plan','Bank Passbook'], 'https://www.mudra.org.in', '', 21, ARRAY['business','loan','msme']),
('Startup India Registration', 'स्टार्टअप इंडिया पंजीकरण', 'ஸ்டார்ட்அப் இந்தியா பதிவு', 'Tax benefits and easier compliance for recognized startups.', 'मान्यता प्राप्त स्टार्टअप के लिए कर लाभ और आसान अनुपालन।', 'அங்கீகரிக்கப்பட்ட ஸ்டார்ட்அப்களுக்கு வரி நலன்கள் மற்றும் எளிதான இணக்கம்.', 'business', 'DPIIT', 'central', '', 'Tax exemption + easier compliance + IPR support', '{"occupation":["entrepreneur"],"tags":["startup"]}', ARRAY['PAN Card','Incorporation Certificate','Business Plan'], 'https://startupindia.gov.in', '', 30, ARRAY['startup','business','tax']),
('Udyam (MSME) Registration', 'उद्यम (एमएसएमई) पंजीकरण', 'உத்யம் (MSME) பதிவு', 'Free online registration for micro, small, and medium enterprises with benefits.', 'सूक्ष्म, लघु और मध्यम उद्यमों के लिए लाभों के साथ निःशुल्क ऑनलाइन पंजीकरण।', 'நுண், சிறு மற்றும் நடுத்தர நிறுவனங்களுக்கு நலன்களுடன் இலவச ஆன்லைன் பதிவு.', 'business', 'Ministry of MSME', 'central', '', 'Subsidies, credit support, and protection against delayed payments', '{"occupation":["entrepreneur"]}', ARRAY['Aadhaar Card','PAN Card','Bank Passbook'], 'https://udyamregistration.gov.in', '', 3, ARRAY['msme','business','registration']),
('Stand-Up India', 'स्टैंड-अप इंडिया', 'ஸ்டாண்ட்-அப் இந்தியா', 'Bank loans between ₹10 lakh and ₹1 crore for SC/ST and women entrepreneurs.', 'एससी/एसटी और महिला उद्यमियों के लिए ₹10 लाख से ₹1 करोड़ तक का बैंक ऋण।', 'பட்டியல்/பழங்குடி மற்றும் பெண் தொழில்முனைவோருக்கு ₹10 லட்சம் முதல் ₹1 கோடி வரை வங்கி கடன்.', 'women', 'Department of Financial Services', 'central', '', 'Loans ₹10 lakh-₹1 crore', '{"gender":["female"],"categories":["SC","ST"],"age_min":18}', ARRAY['Aadhaar Card','PAN Card','Business Plan','Bank Passbook'], 'https://www.standupmitra.in', '', 30, ARRAY['women','entrepreneur','sc-st','loan']),
('Maternity Benefit Program (PMMVY)', 'मातृत्व लाभ कार्यक्रम (पीएमएमवीवी)', 'தாய்மை நலத் திட்டம் (PMMVY)', 'Cash incentive of ₹5,000 to pregnant and lactating mothers for first child.', 'पहले बच्चे के लिए गर्भवती और धात्री माताओं को ₹5,000 का नगद प्रोत्साहन।', 'முதல் குழந்தைக்கு கர்பிணி மற்றும் பாலூட்டும் தாய்மார்களுக்கு ₹5,000 பண ஊக்கத்தொகை.', 'women', 'Ministry of Women and Child Development', 'central', '', '₹5,000 cash benefit', '{"gender":["female"],"tags":["pregnant"]}', ARRAY['Aadhaar Card','Bank Passbook','MCP Card'], 'https://wcd.nic.in', '', 60, ARRAY['women','maternity','cash']),
('Scholarship for Students with Disabilities', 'दिव्यांग छात्रों के लिए छात्रवृत्ति', 'மாற்றுத்திறனாளி மாணவர்களுக்கான உதவித்தொகை', 'Financial assistance to students with 40% or more disability for education.', '40% या अधिक दिव्यांगता वाले छात्रों को शिक्षा के लिए वित्तीय सहायता।', '40% அல்லது அதற்கு மேற்பட்ட மாற்றுத்திறனாளி மாணவர்களுக்கு கல்விக்கான நிதி உதவி.', 'disability', 'Department of Empowerment of Persons with Disabilities', 'central', '', '₹800-₹2,000/month based on level', '{"disability":true,"education":["pre-matric","post-matric"]}', ARRAY['Aadhaar Card','Disability Certificate','Income Certificate','Bonafide Certificate'], 'https://scholarships.gov.in', '2025-12-31', 45, ARRAY['disability','student','scholarship']),
('ADIP Scheme (Assistance for Assistive Devices)', 'एडीआईपी योजना (सहायक उपकरणों के लिए सहायता)', 'ADIP திட்டம் (உதவி கருவிகளுக்கான உதவி)', 'Free aids and appliances to persons with disabilities to improve their mobility.', 'गतिशीलता बढ़ाने के लिए दिव्यांग व्यक्तियों को निःशुल्क सहायक उपकरण।', 'இயக்கத்தை மேம்படுத்த மாற்றுத்திறனாளிகளுக்கு இலவச உதவி கருவிகள்.', 'disability', 'Department of Empowerment of Persons with Disabilities', 'central', '', 'Free assistive devices up to ₹15,000', '{"disability":true,"income_max":25000}', ARRAY['Aadhaar Card','Disability Certificate','Income Certificate'], '', '', 30, ARRAY['disability','assistive-devices']),
('Varishtha Nagrik Tirth Yatra (Senior Pilgrimage)', 'वरिष्ठ नागरिक तीर्थ यात्रा', 'மூத்த குடிமக்கள் தீர்த்த யாத்திரை', 'Subsidized pilgrimage for senior citizens to major religious sites.', 'प्रमुख धार्मिक स्थलों के लिए वरिष्ठ नागरिकों के लिए रियायती तीर्थ यात्रा।', 'முக்கிய புனித தலங்களுக்கு மூத்த குடிமக்களுக்கு மானிய யாத்திரை.', 'senior', 'Government of Delhi', 'state', 'Delhi', '50% travel subsidy', '{"age_min":60,"state":"Delhi"}', ARRAY['Aadhaar Card','Age Proof','Residence Certificate'], '', '', 45, ARRAY['senior','pilgrimage','delhi']),
('Tamil Nadu Free Bus Pass for Senior Citizens', 'तमिलनाडु वरिष्ठ नागरिकों के लिए निःशुल्क बस पास', 'தமிழ்நாடு மூத்த குடிமக்களுக்கான இலவச பேருந்து பாஸ்', 'Free bus travel for senior citizens aged 60+ across Tamil Nadu state buses.', 'तमिलनाडु राज्य बसों में 60+ वर्ष के वरिष्ठ नागरिकों के लिए निःशुल्क बस यात्रा।', 'தமிழ்நாடு மாநில பேருந்துகளில் 60+ வயது மூத்த குடிமக்களுக்கு இலவச பேருந்து பயணம்.', 'senior', 'Government of Tamil Nadu', 'state', 'Tamil Nadu', 'Free bus pass', '{"age_min":60,"state":"Tamil Nadu"}', ARRAY['Aadhaar Card','Age Proof','Residence Certificate'], '', '', 7, ARRAY['senior','transport','tamil-nadu']),
('LPG Subsidy (PAHAL)', 'एलपीजी सब्सिडी (पहल)', 'எல்பிஜி மானியம் (PAHAL)', 'Direct benefit transfer of LPG cooking gas subsidy to the consumer''s bank account.', 'उपभोक्ता के बैंक खाते में एलपीजी रसोई गैस सब्सिडी का सीधा लाभ अंतरण।', 'நுகர்வோர் வங்கி கணக்கில் எல்பிஜி சமையல் எரிவாயு மானியத்தின் நேரடி பயன் பரிமாற்றம்.', 'subsidy', 'Ministry of Petroleum and Natural Gas', 'central', '', 'Subsidy credited to bank account', '{"age_min":18}', ARRAY['Aadhaar Card','Bank Passbook','LPG Consumer Number'], 'https://mylpg.in', '', 7, ARRAY['subsidy','lpg','dbt'])
ON CONFLICT DO NOTHING;

-- ============ offices ============
INSERT INTO offices (name, type, address, district, state, latitude, longitude, services, timings, phone, estimated_wait_mins)
VALUES
('Aadhaar Seva Kendra - Anna Salai', 'aadhaar', 'No. 8, Anna Salai, Chennai', 'Chennai', 'Tamil Nadu', 13.0827, 80.2707, ARRAY['New Aadhaar','Aadhaar Update','Biometric Update','Mobile Update'], 'Mon-Sat 9:00 AM - 5:30 PM', '1947', 45),
('Aadhaar Seva Kendra - Coimbatore', 'aadhaar', 'RS Puram, Coimbatore', 'Coimbatore', 'Tamil Nadu', 11.0168, 76.9558, ARRAY['New Aadhaar','Aadhaar Update','Biometric Update'], 'Mon-Sat 9:00 AM - 5:30 PM', '1947', 60),
('Passport Seva Kendra - Chennai', 'passport', 'Shastri Bhavan, Chennai', 'Chennai', 'Tamil Nadu', 13.0500, 80.2520, ARRAY['Fresh Passport','Renewal','Tatkal Passport','Police Verification'], 'Mon-Fri 9:00 AM - 5:00 PM', '1800-258-1800', 75),
('Passport Seva Kendra - Madurai', 'passport', 'Collectorate Campus, Madurai', 'Madurai', 'Tamil Nadu', 9.9252, 78.1198, ARRAY['Fresh Passport','Renewal','Tatkal Passport'], 'Mon-Fri 9:00 AM - 5:00 PM', '1800-258-1800', 90),
('RTO Office - Chennai Central', 'rto', 'Poonamallee High Road, Chennai', 'Chennai', 'Tamil Nadu', 13.0780, 80.2300, ARRAY['Driving Licence','Vehicle Registration','RC Transfer','Fitness Certificate'], 'Mon-Sat 9:00 AM - 5:00 PM', '044-2641', 120),
('RTO Office - Coimbatore', 'rto', 'Trichy Road, Coimbatore', 'Coimbatore', 'Tamil Nadu', 10.9900, 76.9600, ARRAY['Driving Licence','Vehicle Registration','RC Transfer'], 'Mon-Sat 9:00 AM - 5:00 PM', '0422-230', 120),
('Taluk Office - T Nagar', 'taluk', 'T Nagar, Chennai', 'Chennai', 'Tamil Nadu', 13.0418, 80.2341, ARRAY['Community Certificate','Income Certificate','Residence Certificate','Birth Certificate'], 'Mon-Sat 10:00 AM - 5:00 PM', '044-2432', 60),
('Common Service Centre - Chennai', 'csc', 'Taramani, Chennai', 'Chennai', 'Tamil Nadu', 12.9756, 80.2239, ARRAY['Aadhaar Services','PAN Card','Voter ID','Pension Applications','Bill Payments'], 'Mon-Sun 8:00 AM - 8:00 PM', '1800-3000', 30),
('Collectorate - Chennai', 'collectorate', 'Rajaji Salai, Chennai', 'Chennai', 'Tamil Nadu', 13.0827, 80.2820, ARRAY['Grievance Redressal','Certificates Verification','Public Services'], 'Mon-Fri 10:00 AM - 5:00 PM', '044-2561', 90),
('Government Hospital - GH Chennai', 'hospital', 'Chennai General Hospital, Chennai', 'Chennai', 'Tamil Nadu', 13.0860, 80.2750, ARRAY['PMJAY Treatment','Vaccination','Health Checkup','Emergency Care'], '24x7', '104', 30),
('Police Station - Teynampet', 'police', 'Teynampet, Chennai', 'Chennai', 'Tamil Nadu', 13.0350, 80.2400, ARRAY['FIR Filing','Complaint Registration','Verification','Passport Verification'], '24x7', '100', 20),
('Agriculture Office - Chennai', 'agriculture', 'Koyambedu, Chennai', 'Chennai', 'Tamil Nadu', 13.0690, 80.2040, ARRAY['PM-KISAN Registration','Soil Health Card','Crop Insurance','Subsidy Claims'], 'Mon-Sat 9:00 AM - 5:00 PM', '044-2479', 45)
ON CONFLICT DO NOTHING;
